import Head from 'next/head'
import { Container, Box, Heading, Text, Link } from '@chakra-ui/react'
import { initializeApollo, addApolloState } from '../lib/apolloClient'
import PostList, {
  ALL_POSTS_QUERY,
  allPostsQueryVars,
} from '../components/PostList'
import TimeAgo from 'javascript-time-ago'
import en from 'javascript-time-ago/locale/en.json'
TimeAgo.addDefaultLocale(en)

export default function Home() {
  return (
    <Container maxWidth='container.sm' m="20px auto" bg='blue.100'>
      <Head>
        <title>Lens feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w='100%' m="20px auto" textAlign="center">
        <Heading as="h1" size="xl">
          Lens feed
        </Heading>
      </Box>
      <PostList />
    </Container>
  )
}

export async function getStaticProps() {
  // `getStaticProps` is executed on the server side.
  const apolloClient = initializeApollo()

  await apolloClient.query({
    query: ALL_POSTS_QUERY,
    variables: allPostsQueryVars,
  })

  return addApolloState(apolloClient, {
    props: {},
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every ${revalidate} seconds
    revalidate: 1, // In seconds
  })
}
