import Head from 'next/head'
import { Container, Box, Heading, Text, Link } from '@chakra-ui/react'

export default function Home() {
  return (
    <Container maxWidth='container.lg' m="20px auto">
      <Head>
        <title>Lens feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w='100%' m="20px auto" textAlign="center">
        <Heading as="h1" size="xl">
          Lens feed
        </Heading>
      </Box>
    </Container >
  )
}
