import Head from 'next/head'
import { Container, Box, Heading, Text, Link } from '@chakra-ui/react'

export default function Home() {
  return (
    <Container maxWidth='container.lg' m="20px auto">
      <Head>
        <title>Lens feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w='100%' m="20px auto" textAlign="center">
        <Heading as="h1" size="xl">
          Lens feed
        </Heading>
      </Box>
    </Container >
  )
}

export async function getStaticProps() {
  // `getStaticProps` is executed on the server side.

  return {
    props: {
      // profileTotalSupply: cursor
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  }
}